<?php

/**
 * @file
 * Contains menu_link_placeholder.module.
 */

function menu_link_placeholder_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'menu_link_content') {
    $fields['link']->setRequired(FALSE);
  }
}

/**
 * Implementation of hook_preprocess_HOOK().
 */
function menu_link_placeholder_preprocess_menu(&$variables) {
  foreach ($variables['items'] as $menu_link_key => &$menu_link) {
    _menu_link_placeholder_preprocess_menu_link($menu_link);
  }
}

/**
 * Recursive menu_link item fixer.
 */
function _menu_link_placeholder_preprocess_menu_link(&$menu_link) {
  $route = $menu_link['url']->toUriString();
  if ($route == 'route:') {
    $menu_link['no_link'] = TRUE;
  }

  if (isset($menu_link['below']) && count($menu_link['below'])) {
    foreach ($menu_link['below'] as &$child_menu_link) {
      _menu_link_placeholder_preprocess_menu_link($child_menu_link);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function menu_link_placeholder_preprocess_table__menu_overview(&$variables) {
  foreach ($variables['rows'] as &$row) {
    if ($row['cells'][0]['content'][1]['#url']->toUriString() == 'route:') {
      $title = $row['cells'][0]['content'][1]['#title'];
      $row['cells'][0]['content'][1] = array(
        '#markup' => $title
      );
    }
  }
}
